# Every file here is generated by tools/gen_metadata.py from the Cisco APIC MIM
# Reference, which is also where each file's contents are described. A record of
# model.jsonl is reached by one seek, the file being some megabytes and a caller wanting
# one class of it. Every file loads lazily, so that importing this module costs a tab
# press nothing.

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import Any

_CLASSES_FILE = Path(__file__).with_name("classes.txt")
_RN_FORMATS_FILE = Path(__file__).with_name("rn_formats.txt")
_MODEL_FILE = Path(__file__).with_name("model.jsonl")
_MODEL_INDEX_FILE = Path(__file__).with_name("model.idx")
_SEARCH_FILE = Path(__file__).with_name("search.txt")


@lru_cache(maxsize=1)
def load_class_names() -> tuple[str, ...]:
    return tuple(_CLASSES_FILE.read_text(encoding="utf-8").split())


def class_names_startingwith(prefix: str) -> list[str]:
    lowered = prefix.lower()
    return [name for name in load_class_names() if name.lower().startswith(lowered)]


@lru_cache(maxsize=1)
def load_rn_formats() -> dict[str, str]:
    text = _RN_FORMATS_FILE.read_text(encoding="utf-8")
    return dict(line.split("\t", 1) for line in text.splitlines() if line)


def rn_format(class_name: str) -> str | None:
    return load_rn_formats().get(class_name)


# -- the model ------------------------------------------------------------


@lru_cache(maxsize=1)
def _model_index() -> dict[str, tuple[int, int]]:
    index: dict[str, tuple[int, int]] = {}
    with _MODEL_INDEX_FILE.open(encoding="utf-8") as handle:
        for line in handle:
            if not line.strip():
                continue
            name, offset, length = line.rstrip("\n").split("\t")
            index[name] = (int(offset), int(length))
    return index


# A class the dictionary does not carry is not an error: the fabric may be running a
# release newer than the dictionary, and a caller can still query it.
def describe(class_name: str) -> dict[str, Any] | None:
    location = _model_index().get(class_name)
    if location is None:
        return None
    offset, length = location
    with _MODEL_FILE.open("rb") as handle:
        handle.seek(offset)
        raw = handle.read(length)
    return json.loads(raw)


# rank is assigned by tools/gen_metadata.py, lowest first: an ordinary configurable
# class, a relation between two, one that can only be read, and an abstract one.
@lru_cache(maxsize=1)
def _search_entries() -> tuple[tuple[str, int, str, str], ...]:
    entries: list[tuple[str, int, str, str]] = []
    with _SEARCH_FILE.open(encoding="utf-8") as handle:
        for line in handle:
            parts = line.rstrip("\n").split("\t")
            if len(parts) == 4:
                entries.append((parts[0], int(parts[1]), parts[2], parts[3]))
    return tuple(entries)


# Ordered by where the match landed, then by what kind of class it is -- dozens are
# labelled "Bridge Domain" and only one of them is it -- then by the shorter name, which
# is what tells fvAEPg from cloudAEPgSelector. All three matter, a caller with a limit
# of 3 seeing only the top of this list.
def search(keyword: str, limit: int = 40) -> list[tuple[str, str, str]]:
    lowered = keyword.strip().lower()
    if not lowered:
        return []
    buckets: tuple[list[tuple[str, int, str, str]], ...] = ([], [], [], [])
    for entry in _search_entries():
        name, _, label, summary = entry
        if label.lower() == lowered:
            buckets[0].append(entry)
        elif lowered in name.lower():
            buckets[1].append(entry)
        elif lowered in label.lower():
            buckets[2].append(entry)
        elif lowered in summary.lower():
            buckets[3].append(entry)
    ordered = [
        entry
        for bucket in buckets
        for entry in sorted(bucket, key=lambda e: (e[1], len(e[0]), e[0]))
    ]
    return [(name, label, summary) for name, _, label, summary in ordered[:limit]]
